# Getting started {#getting-started}

## Gear

'Good' gear is at once over-rated and under-rated. Allow us to explain.

## Fitness

Start small. Know your limits, have a bail out.

## Weather

Many guides describe the Tennessee weather in a way like the following:

> In East Tennessee, there are four seasons of weather, including a hot, humid summer, and a cold winter, with temperatures regularly dipping below freezing. Spring and fall bring mild weather, with a lot of variation, especially around the shoulder months of March-April and October-November.

This is mostly true, but it fails to capture what it's _like_ to live in this area. We moved from Michigan---and Michigan is certainly a place in which there are four seasons. Indeed, it sometimes feels like the winter is the longest season in Michigan. That's not the case in Tennessee as the _balance_ between the seasons is different and this has profound impacts. 

We'll try to summarize the _experience_ of each of the seasons in East Tennessee and how the progression of a typical year may unfold. 

### Spring

### Summer

### Fall

### Winter

## Safety

A question that many ask about the Smokies, particularly, but also hiking, generally, has to do with safety concerning a very specific concern: bears. [There are black bears in the Smokies](https://www.nps.gov/grsm/learn/nature/black-bears.htm): around 1,500 of them. 

Moreover, [there are black bears in the Big South Fork area](https://trace.tennessee.edu/cgi/viewcontent.cgi?article=7040&context=utk_gradthes) of the Cumberland Plateau: The latest estimates suggest that a population of around one dozen bears that were introduced in the late 1990s are doing very well and now comprise a population of nearly 1,000 bears. 

Given these numbers of bears and the number of visitors to both parks - [more than 12M to the Smokies in 2020 alone](https://www.nps.gov/grsm/learn/news/park-experiences-more-than-12-million-visits-in-2020.htm), the number of people who are harmed by bears can be instructive. 

<> [There is data](https://outforia.com/danger-parks/#all-data) on the number of people killed in the Smokies. These data provide an important context for a discussion of safety (note, we'll also discuss safety-related issues that don't have to do with death). From 2010-2020, the National Park Service recorded 92 deaths. 42 were from automobile or other transportation-related accidents. 15 were medical/natural deaths. Six were drownings, three were falls, two were poisoning, and 10 were either "environmental" or in the other category. 

The park has seen, on average, more than 10M visitors/year from the 2010-2020 period. In the entire history of the park, [there have been around six bear attacks](https://www.knoxnews.com/story/news/local/2020/09/14/great-smokies-rangers-identify-man-found-dead-park-black-bear-scavenging-his-remains/5793471002/) and there have been two deaths from those attacks (in 2000 and 2020). Considering deaths in the last decade, this suggests that bear attacks are exceedingly rare---on the order of one in one hundred million. 

Something a lot of people mention about the Smokies is the prevalence of bears. From what I can tell, there have been 6-7 bear attacks in the history of the park and two deaths (2000 & 2020) from them. Those are bad, but the park received ~100M visitors from 2010-2019 alone. This suggests that the risk of dying from a bear attack is around in 100M. The risk of being attacked is somewhere around 1 in 30-60M (as it's somewhat unclear when the documented attacks occurred).

## Where to begin

Conveient