# Abrams Creek

|Criterion|Rating|
|--------|---------:|
|Accessibility of location|4|
|Family-friendliness|5|
|Beauty|4|
|Proximity to amenities|4|
|Camping options|5|

## Overview

Abrams Creek is a great place to start if you live in or around Knoxville. The trailhead---the place where one trail (or, often, several trails) begin---is the lowest elevation of any in the park: the trailhead is at 1,168 feet; Knoxville's is 886. For many, it's also the closest trailhead, taking less than an hour to travel to from most parts of Knoxville.

Though accessible, it's not nothing in terms of scenery: It has what we would think of as "National Park-level" beauty. There are many great trails as well as backcountry camping options; many of both are along the creek. This was the first place we traveled as a family in the Smokies; the best thing I can say about Abrams Creek is that we always seem to have fun when we go there.

## Getting There

The drive there is also _mostly_ easy, but with enough excitement to make that part of the adventure interesting. Getting to Abrams Creek involves driving south from the Knoxville past the the Tyson-McGee Airport and then Maryville. Soon after leaving the outskirts of Maryville, the road climbs up <add ridge name> with the Foothills Parkway; the road becomes quite steep, but still accessible. After crossing under the Foothills Parkway, you drive down into the area outside of the Abrams Creek Trailhead and Campground.

## Getting One's Bearings

It never seems to become crowded at Abrams Creek, but parking can be _a bit_ confusing. This is because the campground is further along the same road the trailhead is on. Also, there are two areas to park for the trailhead: One is near the large sign with maps of this area of the National Park, and the other is right before the gate that is closed when the campground closes (<dates>). We usually park by the gate.

## Trails

There are <x> trails that we enjoy.

### Little Adventure

A little adventure involves walking from the trailhead to the campground. This may not sound like much, but it's actually a great walk along the creek on a wide, gravel road. Moreover, the campground - like Abrams Creek - is almost never full, apart from prime weekends and holidays, and it's a great spot to rest by picnic tables and hang out around the creek. 



### Medium-Sized Adventure

### Big Adventure