# (PART) The Smokies {-}

# Introduction to the Smokies

## Why it can be hard to understand the Smokies

The Smokies can be a bit hard to get one's head around at first.

It can be hard to get one's head around the Smokies for several reasons:

- Their size: [more than 800 square miles](https://www.nps.gov/grsm/learn/nature/index.htm)
- Their location: split roughly between Tennessee and North Carolina, there are many ways to access the park, and there isn't a _primary_ or _best_ way to do so
- Their variation in altitude: [Abrams Creek---the trailhead nearest to Knoxville---is roughly 850 feet above sea level, whereas Clingman's Dome is roughly 6,650 feet above sea level](https://www.nps.gov/grsm/learn/nature/mountains.htm)
- Their biodiversity: [it may be the most biodiverse National Park](https://www.nps.gov/grsm/learn/nature/index.htm)
- Their human history: thousands of people of European ancestry lived in what is now the National Park up until as recently as 1934 (when the park was established); before people of European ancestry lived there, thousands of people of Cherokee ancestry lived there; these histories remain alive and present within the park

I think these reasons are important in general and in a bit of an abstract sense, but they also have a more personal angle: The Smokies are hard to _experience_ for each of these and other reasons, too. They appear and are different in different seasons. They are very different when experienced when walking than when driving in a car. They are different when it's rainy and when it's not. And, they are different alone, with family, with friends, and with a child. 

## A bit on my understanding of the Smokies

When my wife and I first decided to move to Knoxville, I began trying to understand the Smokies, and since then I've read a lot of books and spent a lot of time there. I don't think I can adequately summarize the Smokies, but I can begin to convey my understanding. 

The Smokies are a timeless place, at once welcoming and severe. When I drive to the Smokies, I feel like I'm entering into a special place. That special feeling is amplified by the good memories I've had there---with my family and friends and on my own. 

I value living by the Smokies a lot. This is a function of a lot of things coming together: stopping refereeing soccer, something I'd done for around 12 years up to that point, soon after we moved to Knoxville, the pandemic, which prevented many other activities from happening, and a live for doing things outdoors that motivated me to study biology and enter teaching to begin. 

I'll describe just one trip to try to work to summarize my understanding of the Smokies.

In May, 2020, my wife and little one and I hiked the beginning of the Bote Mountain and West Prong trails to the location of Backcountry site #18. It was one of our first times heading out after the pandemic began, and it was a moderately difficult hike - around three miles, but with nearly 1,000 feet of climbing. When we arrived at the site---where two creeks meet and are crossed by a log bridge---there were butterflies everywhere, which the little was overjoyed about.

This was one trip, and it was probably one that we planned on a whim, picking the trail based on what was within an hour's drive. That's what made it special; there wasn't anything particularly distinctive about that trail, hike, or day (except for the butterflies, which were pretty neat), and both this absence of distinctiveness coupled with a sense of someting special has nearly always been the case for the time I've spent in the Smokies.

So, as a bit of a thesis, it's hard to understand the Smokies: they're too large, varied, and rich. But, it is possible to experience the Smokies, and doing so doesn't require making it to Mt. LeConte or Abrams Falls or Clingman's Dome (though each of those are pretty great). One can perhaps have just as positive of an experience as at those (sometimes busy) sites off trails or at picnic areas in the Big Creek, Cosby, and Tremont areas. 

Another example was also on the Cades Cove area. This was near an area called Point host sync. I got hiking with my son and friend and his two children on the schoolhouse gap trail a good if not slightly.

---

But halfway through two people asked us where white oak sticks are having not heard of it before we looked on the map and saw it looked like it was basically in the middle of nowhere with no trails to it. After talking with several more people, we learned that white oak sick is a steep wildflower area. That is especially gorgeous around April, the time that we were there. We found the not on maps trail to widow sick and had out there with her kids. And something changed. Far after beating on the trail. It seemed like a different place where the trees were a bit larger and the sun a bit brighter. And there was just a permeating sense that this was simply special one last story that captures him smoking magic was heading with my wife it's not to backcountry site 18 Not to camp but just to use that area. As a stopping point on an approximately three mile hike, The hike was good and the weather was great. But when we got to the countryside, there was just something in there. The light was perfect. The two creeks that flowed together are magical. And there were butterflies everywhere. Our son couldn't stop giggling and chasing them I can go on with stories like this of the Father's day hike in Abrams Creek or riving. Up at Mount Collins on January hike with my friend Kevin. Or coming down to our caves from Ellicott for the first time or seeing Big Creek with my son these are the kinds of things that capture this book.

Notably, none of them necessarily involve most famous parts of the park. Sometimes they do but more often they don't get more subtle and surprising and rewarding.

---