library(ggmap)
library(sf)
library(tidyverse)
library(ggmap)
library(osmdata)
library(geosphere)
library(ggsn)
library(slopes)
library(showtext)
library(cowplot)
library(here)
library(ggspatial)
library(terra)
library(ggrepel)
library(ggsflabel) # devtools::install_github("yutannihilation/ggsflabel")

source("gaia-trails.R")
source("create_abrams-trail-map.R")