library(ggmap)
library(sf)
library(tidyverse)
library(ggmap)
library(osmdata)
library(geosphere)
library(ggsn)
library(slopes) # # install.packages("remotes")
library(showtext)
library(cowplot)
library(here)
library(ggspatial)
library(terra)
library(ggrepel)
library(ggsflabel) # devtools::install_github("yutannihilation/ggsflabel")
# library(sysfonts)
# library(showtext)

set.seed(20210122)

source("gaia-trails.R")

# smokies
# source("create-middle-prong-trail-map.R")
source("create-white-oak-sinks.R")
source("create-abrams-trail-map.R")
source("create-abrams-falls-map.R")
source("create-big-creek-map.R")
source("create-andrews-bald-map.R")
source("create-alum-cave-map.R")
source("create-little-river-loop-trail-map.R")


# tn valley
source("create-seven-islands-map.R")
source("create-ijams-crag-map.R")
source("create-house-mountain-overlook-map.R")
source("create-knox-blount-map.R")
source("create-william-hastie-map.R")
source("create-lakeshore-map.R")

# cumberland
source("create-songbird-loop-map.R")
source("create-emory-falls-map.R")
source("create-interpretive-trail-map.R")
source("create-angel-falls-overlook-map.R")
source("create-bandy-creek-map.R")
source("create-honey-creek-map.R")
source("create-obed-point-trail-map.R")
source("create-twin-arches-map.R")